name: uni_ocr_api
description: ''
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ocr_engine_youdao: ^0.1.1
  shelf: ^1.1.0
  shelf_router: ^1.1.2
  uni_ocr_client: ^0.1.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner:
